# Generated by Django 6.0.2 on 2026-03-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone No.')),
                ('product_description', models.TextField(blank=True, verbose_name='Product Description')),
                ('machine_make', models.CharField(max_length=100, verbose_name='Machine Make')),
                ('machine_model', models.CharField(max_length=100, verbose_name='Machine Model')),
                ('part_number', models.CharField(blank=True, max_length=100, verbose_name='Part Number')),
                ('hose_designation', models.CharField(max_length=100, verbose_name='Gates Hose Designation')),
                ('cut_length', models.FloatField(verbose_name='Hose cut length (meters)')),
                ('coupling_a', models.CharField(max_length=100, verbose_name='A - Coupling')),
                ('coupling_b', models.CharField(max_length=100, verbose_name='B - Coupling')),
                ('demand_cycle', models.IntegerField(default=30, verbose_name='Demand cycle (days)')),
                ('hose_size', models.CharField(choices=[('1/4', '1/4"'), ('3/8', '3/8"'), ('1/2', '1/2"'), ('3/4', '3/4"'), ('1', '1"'), ('1.1/4', '1.1/4"')], max_length=20, verbose_name='Hose Size')),
                ('status', models.CharField(choices=[('Sold', 'Sold'), ('Lost Sale', 'Lost Sale')], default='Sold', max_length=20)),
                ('lost_reason', models.CharField(blank=True, choices=[('Price', 'High Price'), ('Stock', 'Out of Stock'), ('Fitting', 'Fitting Mismatch'), ('Time', 'Long Waiting Time')], max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Price (ETB)')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
            ],
        ),
    ]
