# Generated by Django 5.1.3 on 2026-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0002_alter_hoserecord_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoserecord",
            name="customer_name",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="hoserecord",
            name="psi",
            field=models.IntegerField(default=0, verbose_name="PSI Value"),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="hose_size",
            field=models.CharField(
                choices=[
                    ("1/4", "1/4"),
                    ("3/8", "3/8"),
                    ("1/2", "1/2"),
                    ("3/4", "3/4"),
                    ("1", "1"),
                    ("1.1/4", "1.1/4"),
                ],
                max_length=20,
                verbose_name="Hose Size",
            ),
        ),
    ]
