# Generated by Django 5.2.12 on 2026-03-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0003_hoserecord_customer_name_hoserecord_psi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoserecord",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Contact Phone No."
            ),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="coupling_a",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="A - Coupling"
            ),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="coupling_b",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="B - Coupling"
            ),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="customer_name",
            field=models.CharField(
                blank=True, default="Unknown", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="cut_length",
            field=models.FloatField(
                default=0.0, verbose_name="Hose cut length (meters)"
            ),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="hose_designation",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Gates Hose Designation",
            ),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="hose_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1/4", "1/4"),
                    ("3/8", "3/8"),
                    ("1/2", "1/2"),
                    ("3/4", "3/4"),
                    ("1", "1"),
                    ("1.1/4", "1.1/4"),
                ],
                max_length=20,
                null=True,
                verbose_name="Hose Size",
            ),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="part_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Part Number"
            ),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="product_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Product Description"
            ),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="Remark"),
        ),
    ]
