# Generated by Django 5.2.12 on 2026-03-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0004_alter_hoserecord_contact_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoserecord",
            name="date",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Date"),
        ),
    ]
