# Generated by Django 5.1.3 on 2026-03-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0005_alter_hoserecord_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hoserecord",
            name="customer_name",
        ),
        migrations.AddField(
            model_name="hoserecord",
            name="tin_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="TIN Number"
            ),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="machine_make",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Machine Make"
            ),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="machine_model",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Machine Model"
            ),
        ),
        migrations.AlterField(
            model_name="hoserecord",
            name="psi",
            field=models.IntegerField(
                default=0, help_text="Working Pressure in PSI", verbose_name="PSI"
            ),
        ),
    ]
