# Generated by Django 5.1.3 on 2026-03-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0006_remove_hoserecord_customer_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proforma",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proforma_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Proforma Number"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="Customer Name"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Total Amount (ETB)",
                    ),
                ),
                (
                    "prepared_by",
                    models.CharField(max_length=100, verbose_name="Prepared By"),
                ),
            ],
            options={
                "verbose_name": "Proforma",
                "verbose_name_plural": "Proformas",
            },
        ),
    ]
