# Generated by Django 5.1.3 on 2026-03-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0007_proforma"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proforma",
            options={},
        ),
        migrations.AddField(
            model_name="proforma",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Grand Total"
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="sub_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Sub Total"
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="terms_and_conditions",
            field=models.TextField(
                default="Validity: 3 days. Delivery: Immediate.", verbose_name="Terms"
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="vat_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="VAT (15%)"
            ),
        ),
        migrations.CreateModel(
            name="ProformaItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Item Description"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Unit Price"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=12,
                        verbose_name="Total Price",
                    ),
                ),
                (
                    "proforma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="crm_app.proforma",
                    ),
                ),
            ],
        ),
    ]
