# Generated by Django 5.1.3 on 2026-03-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0008_alter_proforma_options_proforma_grand_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proforma",
            name="grand_total",
        ),
        migrations.RemoveField(
            model_name="proforma",
            name="sub_total",
        ),
        migrations.RemoveField(
            model_name="proforma",
            name="terms_and_conditions",
        ),
        migrations.RemoveField(
            model_name="proforma",
            name="vat_amount",
        ),
    ]
