# Generated by Django 5.1.3 on 2026-03-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0009_remove_proforma_grand_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proforma",
            name="sub_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="Sub Total (ETB)",
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="terms_and_conditions",
            field=models.TextField(
                default="Validity: 3 days. Delivery: Immediate.", verbose_name="Terms"
            ),
        ),
        migrations.AddField(
            model_name="proforma",
            name="vat_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="VAT (15%)",
            ),
        ),
        migrations.AlterField(
            model_name="proforma",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="Grand Total (ETB)",
            ),
        ),
    ]
