"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$p$07d-_)&8e1n1*8jt%@=#7%nintd298ocwda9gb8$%==dpsx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ሁሉንም እንዲቀበል '*' ምልክት ተጠቀም ወይም የሰርቨሩን IP ጨምር
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',  # <--- ዋናው መተግበሪያ ይሄ ብቻ ነው መሆን ያለበት
    'crm_app',        # ያንተ አፕ መኖሩንም አረጋግጥ
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'core.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'core.wsgi.application'
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'uniqueuna7@gmail.com'
EMAIL_HOST_PASSWORD = 'ijkbddehwzupgtqx'
# የአድሚን ገጽ ከለርን ለመቀየር
# ይህ ከለሩን ወደ ቀይ (Dark Red) ይቀይረዋል
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# ማሳሰቢያ፡ ይህንን በ templates ውስጥ ባለው context_processor መጠቀም ይቻላል
# ወይም ደግሞ ቀላሉ መንገድ በ crm_app/admin.py ውስጥ Header መቀየር ነው
# የአድሚን ገጽ ከለርን በቀጥታ መቀየሪያ
from django.contrib import admin
admin.AdminSite.enable_nav_sidebar = True
# Excel (xlsx) እንዲሰራ የሚፈቅድ ኮድ
# መጀመሪያ ከላይ እነዚህን መስመሮች መኖራቸውን አረጋግጥ
import import_export.formats.base_formats

# ከዚያ ዝርዝሩን እንዲህ ብቻ ጻፈው
IMPORT_EXPORT_FORMATS = [
    import_export.formats.base_formats.CSV,
    import_export.formats.base_formats.XLSX
]
IMPORT_EXPORT_FORMATS = [import_export.formats.base_formats.CSV, import_export.formats.base_formats.XLSX]
# ለ5 ደቂቃ (300 ሰከንድ) ምንም ካልተሰራ በራሱ Logout እንዲያደርግ
SESSION_COOKIE_AGE = 300
SESSION_SAVE_EVERY_REQUEST = True
